### ISSUE TITLE
URGENT: Introduced incompatability?

### ISSUE THREAD

**Issue by qabi** [windkh/node-red-contrib-shelly#158]
After upgrade to 10.25.1 I get the following message with a Pro3EM:

> Shelly type mismatch: SPEM-003CEBEU. Choose correct type or if the device is not supported yet then report it here: https:// github.com/windkh/node-red-contrib-shelly/issues

Firmware on device is 1.3.2.

How can I fix this?

**Comment by qabi** [comment]
Seems to be an issue with multiple nodes. After deleting all but one it works. Could also be a strange configuration error.

**Comment by qabi** [comment]
Seems to be an issue with multiple nodes, or possibly a strange configuration issue in my setup.

**Comment by windkh** [comment]
@qabi under normal circumstances there should not be a problem:
I assume that you have chosen gen 2 node and the type "measure" device from the list: "SPEM-*"
SPEM-003CEBEU is a "shelly pro 3em". I wonder why it is not detected correctly. Maybe you choose the device "shelly pro 3em" instead of "measure" from the list in the config of the node

**Comment by qabi** [comment]
Sorry, I tried closing this issue again, as it seems to be fixed now for me. At least for a single node usage.

**Comment by qabi** [comment]
Unclear. I had three nodes for this device, all used to work. Errors started after recent upgrade. I checked settings, and they all seemed correct, but the problem was still there. After removing two of the nodes, so there is only one left (used in multiple flows) it seems to work fine now :)
